web:
  image: nginx
  container_name: reverse-proxy
  volumes:
   - ./configs:/etc/nginx/conf.d
   - ./configs:/etc/nginx/cond.d
  ports:
   - "80:80"
  environment:
   - NGINX_HOST=krux.me
   - NGINX_PORT=80
  restart: unless-stopped